name: Build Vue
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 * * * *"
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2

    - name: Build
      env:
        ACTION_GITHUB_TOKEN: ${{ secrets.AA_GITHUB_TOKEN }}
      run: |
        npm ci
        npm run build
        npm run getdata
        cd dist
        git config --global user.email "bot@hotdry.top"
        git config --global user.name "hotdry-bot"
        git init
        git add -A
        git commit -m "deploy"
        git push -f https://zy6p:$ACTION_GITHUB_TOKEN@github.com/zy6p/covid-19-dashboard.git master:gh-pages
      shell: bash
